# syntax=docker/dockerfile:1@sha256:4edf897a3ffa55b89f906fc8cc78afdb3f1834cc9c7083565e611a8a7d5fe99e

FROM mcr.microsoft.com/devcontainers/base:trixie@sha256:6ee2b4097c75d33e9a94d941577a3286e5d629434fba384688b06daeeaaeac99 AS dev

# Note: The user vscode already exists by default in Microsofts base images
ARG USERNAME=vscode

# renovate: datasource=node-version depName=node versioning=node
ARG NODE_VERSION=24
# renovate: datasource=npm depName=corepack
ARG COREPACK_VERSION=0.36.0
# renovate: datasource=npm depName=playwright
ARG PLAYWRIGHT_VERSION=1.63.0
# renovate: datasource=github-releases depName=terrastruct/d2 versioning=semver extractVersion=^v(?<version>.*)$
ARG D2_VERSION=0.9.0
# renovate: datasource=github-releases depName=aquasecurity/trivy versioning=semver extractVersion=^v(?<version>.*)$
ARG TRIVY_VERSION=0.75.0

USER root
WORKDIR /app

#? Install gosu (sudo alternative for containers)
RUN apt-get update \
  && apt-get install -y --no-install-recommends gosu \
  && rm -rf /var/lib/apt/lists/*


RUN curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash - \
  && apt-get update \
  && apt-get install -y --no-install-recommends nodejs \
  && rm -rf /var/lib/apt/lists/* \
  && node --version


RUN npm install -g corepack@${COREPACK_VERSION} \
  && corepack --version \
  && corepack enable


#? Install only system dependencies (not Playwright nor Chromium browser) for Playwright Chromium
RUN npx -y playwright@${PLAYWRIGHT_VERSION} install-deps chromium


# Install D2
RUN curl -fsSL https://d2lang.com/install.sh \
  | sh -s -- \
    --method=standalone \
    --prefix=/usr/local \
    --version "${D2_VERSION}" \
  && d2 --version


# Install Trivy
RUN curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v${TRIVY_VERSION} \
  && trivy --version


#? Input the entrypoint.sh script and set executable permissions to it
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
