dedupePeers: true
minimumReleaseAge: 2160 #* minutes; applies for transition deps as well
allowBuilds:
  esbuild: true
  lefthook: true
  oxc-resolver: true
saveExact: true
overrides:
  "picomatch@2": "2.3.2"
