name: CI Pipeline

on:
  push:
    branches: [main, dev] #* Not needed, just security fallback
  pull_request:
    branches: [main, dev]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '24'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Knip production check
        run: npm run knip:prod
      - name: Run Dependency Cruiser check
        run: npm run dep-cruise:check
      - name: Run TypeScript type check
        run: npm run check:types
      - name: Run Biome lint check
        run: npm run lint:check
