name: CI Pipeline

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'

  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Run Knip production check
        run: npm run knip:prod
      - name: Run Dependency Cruiser check
        run: npm run dep-cruise:check
      - name: Run TypeScript type check
        run: npm run check:types
      - name: Run Biome lint check
        run: npm run lint:check

  build:
    needs: validate
    uses: ./.github/workflows/build-image.yml
    permissions: #* nested workflows cannot escalate permissions
      packages: write     #? needed for build-image.yml
      contents: read      #? needed for build-image.yml

  tests:
    needs: [validate, build]
    uses: ./.github/workflows/tests.yml
    with:
      run-unit: true
      run-component: true
      run-integration: false

  e2e:
    needs: [ validate, build, tests ]
    uses: ./.github/workflows/e2e.yml
    with:
      image-tag: ${{ needs.build.outputs.image-tag }}
      run-e2e: false
    permissions:          #* nested workflows cannot escalate permissions
      packages: read
      checks: write       #? needed for JUnit reporting tests.yml
      contents: read

  trivy-image-scan:
    needs: build
    uses: ./.github/workflows/trivy-scan-image.yml
    with:
      image-tag: ${{ needs.build.outputs.image-tag }}
    permissions:
      contents: read
      security-events: write
      packages: write
