name: CI Pipeline

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'

  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write  #? For node caching
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: 10
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: '24'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Knip production check
        run: pnpm run knip:prod
      - name: Run Dependency Cruiser check
        run: pnpm run depcruise:check
      - name: Run TypeScript type check
        run: pnpm run check:types
      - name: Run Biome lint check
        run: pnpm run lint:check

  build:
    needs: validate
    uses: ./.github/workflows/build-image.yml
    permissions: #* nested workflows cannot escalate permissions
      packages: write     #? needed for build-image.yml
      contents: read      #? needed for build-image.yml

  tests:
    needs: [validate, build]
    uses: ./.github/workflows/tests.yml
    with:
      run-unit: true
      run-component: true
      run-integration: true
    permissions:
      contents: read
      actions: write      #? For node caching

  e2e:
    needs: [validate, build, tests]
    uses: ./.github/workflows/e2e.yml
    with:
      image-tag: ${{ needs.build.outputs.image-tag }}
      run-e2e: false
    permissions:          #* nested workflows cannot escalate permissions
      packages: read
      checks: write       #? needed for JUnit reporting tests.yml
      contents: read

  check-fast-forward:
    needs: [validate, build]
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      #* We appear to need write permission for both pull-requests and
      #* issues in order to post a comment to a pull request.
      pull-requests: write
      issues: write

    steps:
      - name: Checking if fast forwarding is possible
        uses: sequoia-pgp/fast-forward@ea7628bedcb0b0b96e94383ada458d812fca4979 # v1.0.0
        with:
          merge: false
          comment: on-error

  trivy-image-scan:
    needs: build
    uses: ./.github/workflows/trivy-scan-image.yml
    with:
      image-tag: ${{ needs.build.outputs.image-tag }}
    permissions:
      contents: read
      security-events: write
      packages: write
